# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='mc_test_passed_responses',
            new_name='mc_passed_responses',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='mc_test_questions',
            new_name='mc_questions',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='mc_test_responses',
            new_name='mc_responses',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='writing_test_questions',
            new_name='writing_questions',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='writing_test_responses',
            new_name='writing_responses',
        ),
    ]
