# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('match_id', models.PositiveSmallIntegerField()),
                ('writing_test_questions', models.TextField(blank=True, default='[]', null=True)),
                ('writing_test_responses', models.TextField(blank=True, default='{}', null=True)),
                ('writing_test_start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('writing_test_end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('mc_test_questions', models.TextField(blank=True, default='[]', null=True)),
                ('mc_test_responses', models.TextField(blank=True, default='{}', null=True)),
                ('mc_test_passed_responses', models.PositiveIntegerField(default=0)),
                ('mc_test_start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('mc_test_end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contestant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('contestant', 'match_id')]),
        ),
    ]
