# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='use_mc_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='use_writing_test',
            field=models.BooleanField(default=False),
        ),
    ]
