# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170304_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='mc_test_questions',
            new_name='mc_questions',
        ),
    ]
