# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170302_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='mc_test_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='mc_test_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='writing_test_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
