# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170302_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='maximum_of_matches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
